name: Ping Many Sitemaps

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ping all sitemap URLs from file
        run: |
          while IFS= read -r URL
          do
            echo "🔄 Pinging Google: $URL"
            curl -s -o /dev/null -w "Google Status: %{http_code}\n" "https://www.google.com/ping?sitemap=$URL"

            echo "🔄 Pinging Bing: $URL"
            curl -s -o /dev/null -w "Bing Status: %{http_code}\n" "https://www.bing.com/ping?sitemap=$URL"

            sleep 1  # optional: be polite
          done < sitemaps.txt
